### ISSUE TITLE
Supported changes of settings frontend <-> xcsoar

### ISSUE THREAD

**Issue by Simsys** [larus-breeze/sw_algorithms_lib#28]
The Larus NMEA interface allows settings to be exchanged between the front end and XCSoar. For this function to be usable, the sensor box must support this in both directions: Frontend -> XCSoar (CAN -> NMEA) and XCSoar -> Frontend (NMEA -CAN).

This concerns the data points MacCready, water ballast, bugs and QNH.

see 
  - [NMEA $PLARS Settings Parameter Bidirectional](https://github.com/larus-breeze/doc_larus/blob/master/documentation/Larus_NMEA_Protocol.md#plars-settings-parameters-bidirectional)
  - [CAN bus Set System Wide Config Item](https://github.com/larus-breeze/doc_larus/blob/master/documentation/can_details/object_directory/sensorbox.md#id-0x522-set-system-wide-config-item)

**Comment by MaxBaex** [comment]
Related to https://github.com/larus-breeze/sw_sensor/issues/19
